import json
import os
from pathlib import Path
from typing import Dict

from xml.etree.ElementTree import Element, SubElement, tostring

from ..core import AppContext
from ..core.models import RecordedMediaEntry, RecordedMediaLine


def _indent(elem, level=0):
    i = "\n" + level * "  "
    if len(elem):
        if not elem.text or not elem.text.strip():
            elem.text = i + "  "
        for child in elem:
            _indent(child, level + 1)
        if not child.tail or not child.tail.strip():
            child.tail = i
    if level and (not elem.tail or not elem.tail.strip()):
        elem.tail = i


def _write_metadata(parent: Element, metadata: Dict[str, str]) -> None:
    if not metadata:
        return
    meta_elem = SubElement(parent, "Metadata")
    for key, value in metadata.items():
        SubElement(meta_elem, "Property", key=key, value=str(value or ""))


def export_radio_data(context: AppContext, output_dir: Path):
    root = Element("RadioData")
    root_info = SubElement(root, "RootInfo")
    SubElement(root_info, "SourceFile").text = "SurvivorSignalReboot"
    SubElement(root_info, "FileGUID").text = "00000000-0000-0000-0000-000000000000"
    SubElement(root_info, "Version").text = "1"

    voices_node = SubElement(root, "Voices")
    for voice in context.project.voices.values():
        entry = SubElement(voices_node, "VoiceEntry", ID=voice.id)
        color = voice.color.lstrip("#")
        if len(color) == 6:
            r = int(color[0:2], 16)
            g = int(color[2:4], 16)
            b = int(color[4:6], 16)
        else:
            r = g = b = 255
        SubElement(entry, "FinalColor", r=str(r), g=str(g), b=str(b))
        _write_metadata(entry, voice.metadata)

    channels_node = SubElement(root, "Channels")
    for channel in context.project.channels.values():
        channel_elem = SubElement(
            channels_node,
            "ChannelEntry",
            ID=channel.id,
            name=channel.name,
            cat=channel.category.capitalize(),
            freq=str(int(channel.frequency * 100)),
            startscript=channel.start_script or "main",
            advertGroup=channel.default_advert_group or "",
        )
        for entry in channel.schedule:
            bcast = context.project.broadcasts.get(entry.broadcast_id)
            if not bcast:
                continue
            bc_elem = SubElement(
                channel_elem,
                "BroadcastEntry",
                ID=bcast.id,
                timestamp=str(int(entry.start)),
                endstamp=str(int(entry.end)),
                type="ActivateBroadcast",
                day=str(entry.day),
                advertCat=channel.id,
                isSegment="false",
            )
            _write_metadata(bc_elem, bcast.metadata)
            for line in bcast.lines:
                color = "#ffffff"
                voice = context.project.voices.get(line.voice_id)
                if voice:
                    color = voice.color
                r = int(color[1:3], 16) if len(color) > 1 else 255
                g = int(color[3:5], 16) if len(color) > 3 else 255
                b = int(color[5:7], 16) if len(color) > 5 else 255
                attrs = {"ID": line.guid, "r": str(r), "g": str(g), "b": str(b)}
                if line.effects:
                    attrs["codes"] = ",".join(line.effects)
                line_elem = SubElement(bc_elem, "LineEntry", **attrs)
                line_elem.text = line.text
                _write_metadata(line_elem, line.metadata)

    _indent(root)
    data = tostring(root, encoding="utf-8")
    (output_dir / "RadioData.xml").write_bytes(data)


def export_recorded_media(
    context: AppContext, output_dir: Path, translation_dir: Path | None = None
):
    translation: Dict[str, str] = {}
    lua_path = output_dir / "recorded_media.lua"
    with lua_path.open("w", encoding="utf-8") as lua_file:
        lua_file.write("-- Generated by Survivor Signal Reboot\n")
        lua_file.write("RecMedia = RecMedia or {}\n\n")
        for entry in context.project.recorded_media.values():
            title_key = f"RM_{entry.id}_title"
            translation[title_key] = entry.title
            author_key = f"RM_{entry.id}_author"
            translation[author_key] = entry.author
            extra_key = f"RM_{entry.id}_extra"
            translation[extra_key] = entry.extra or ""

            lua_file.write(f'RecMedia["{entry.id}"] = {{\n')
            lua_file.write(f'\titemDisplayName = "{title_key}",\n')
            lua_file.write(f'\ttitle = "{title_key}",\n')
            lua_file.write("\tsubtitle = nil,\n")
            lua_file.write(f'\tauthor = "{author_key}",\n')
            lua_file.write(f'\textra = "{extra_key}",\n')
            lua_file.write(f"\tspawning = {entry.spawn},\n")
            lua_file.write(f'\tcategory = "{entry.category}",\n')
            lua_file.write("\tlines = {\n")
            for line in entry.lines:
                text_key = f"RM_{line.guid}"
                translation[text_key] = line.text
                codes = line.codes or ""
                lua_file.write(
                    f'\t\t{{ text = "{text_key}", r = {line.r:.2f}, g = {line.g:.2f}, b = {line.b:.2f}, codes = "{codes}" }},\n'
                )
            lua_file.write("\t},\n")
            lua_file.write("};\n\n")

    lines = []
    for k, v in translation.items():
        safe = str(v or "").replace('"', '\\"')
        lines.append(f'{k} = "{safe}"')
    trans_dir = translation_dir or output_dir
    trans_dir.mkdir(parents=True, exist_ok=True)
    (trans_dir / "Recorded_Media_EN.txt").write_text(
        "// Auto-generated by Survivor Signal Reboot\n" + "\n".join(lines),
        encoding="utf-8",
    )
